apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" . }}-config
  namespace: {{ $.Release.Namespace }}
data:
  redis.conf: |
    protected-mode "no"
    port {{ .Values.service.ports.redis }}
    tcp-backlog 511
    unixsocket "/data/redis.sock"
    timeout 60
    tcp-keepalive 0
    daemonize no
    supervised no
    pidfile "/data/redis.pid"
    loglevel notice
    logfile "/data/redis.log"
    databases "16"
    always-show-logo yes
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename "dump.rdb"
    dir "/data/"
    requirepass {{ .Values.auth.password }}
    maxclients 10000
    maxmemory 1024mb
    maxmemory-policy volatile-lru
    maxmemory-samples 5
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    replica-lazy-flush no
    appendonly no
    appendfilename appendonly.aof
    appendfsync no
    no-appendfsync-on-rewrite yes
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 512mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    lua-time-limit 5000
    slowlog-log-slower-than 5000
    slowlog-max-len 10000
    latency-monitor-threshold 0
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes